linux build test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,6 +5,7 @@ on:
       - aplay-pro-release
       - aplay-pro-pre-release
       - aplay2-backup
+      - aplay-pro-linux-build
     tags:
       - "v*"
   workflow_dispatch:
@@ -29,81 +30,83 @@ jobs:
   #          else
   #            echo "result=false" >> $GITHUB_OUTPUT
   #          fi
-  publish_windows:
-    name: "Publish Windows"
-    runs-on: windows-latest
-    permissions:
-      contents: read
-    #      id-token: write # REQUIRED for Azure OIDC
+#  publish_windows:
+#    name: "Publish Windows"
+#    runs-on: windows-latest
+#    permissions:
+#      contents: read
+#    #      id-token: write # REQUIRED for Azure OIDC
+#
+#    steps:
+#      - name: Check out Git repository
+#        uses: actions/checkout@v4
+#
+#      - name: Install Node.js and NPM
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 22
+#
+#      - name: Install dependencies
+#        # npm ci is better, but requires package-lock.json file
+#        run: npm install
+#
+#      - name: Cache Electron artifacts
+#        uses: actions/cache@v4
+#        with:
+#          path: |
+#            ~/.cache/electron
+#            ~/.cache/electron-builder
+#          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
+#
+#      - run: az logout || true
+#
+#      #      - name: Azure Login (OIDC)
+#      #        uses: azure/login@v2
+#      #        with:
+#      #          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+#      #          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+#      #          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+#      #      #   enable-AzPSSession: true
+#
+#      #      - name: Azure Login (Service Principal)
+#      #        uses: azure/login@v2
+#      #        with:
+#      #          auth-type: SERVICE_PRINCIPAL
+#      #          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+#      #          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+#      #          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+#      #          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
+#
+#      - name: Export Azure env vars for Trusted Signing
+#        shell: pwsh
+#        run: |
+#          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $env:GITHUB_ENV
+#          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $env:GITHUB_ENV
+#          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $env:GITHUB_ENV
+#          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $env:GITHUB_ENV
+#
+#      - name: Debug GitHub context
+#        run: |
+#          echo "Ref: $GITHUB_REF"
+#          echo "Repository: $GITHUB_REPOSITORY"
+#
+#      - name: Verify Azure env vars
+#        shell: pwsh
+#        run: |
+#          Get-ChildItem Env:AZURE*
+#
+#      #          echo "Federated token file:"
+#      #          Test-Path $env:AZURE_FEDERATED_TOKEN_FILE
+#
+#      # Build Windows artifacts
+#      - name: Build Windows App
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+#          ELECTRON_BUILDER_HTTP_TIMEOUT: 600000
+#          ELECTRON_BUILDER_HTTP_RETRY: 5
+#        run: npm run release
+#
 
-    steps:
-      - name: Check out Git repository
-        uses: actions/checkout@v4
-
-      - name: Install Node.js and NPM
-        uses: actions/setup-node@v4
-        with:
-          node-version: 22
-
-      - name: Install dependencies
-        # npm ci is better, but requires package-lock.json file
-        run: npm install
-
-      - name: Cache Electron artifacts
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cache/electron
-            ~/.cache/electron-builder
-          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
-
-      - run: az logout || true
-
-      #      - name: Azure Login (OIDC)
-      #        uses: azure/login@v2
-      #        with:
-      #          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-      #          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-      #          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-      #      #   enable-AzPSSession: true
-
-      #      - name: Azure Login (Service Principal)
-      #        uses: azure/login@v2
-      #        with:
-      #          auth-type: SERVICE_PRINCIPAL
-      #          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-      #          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-      #          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-      #          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
-
-      - name: Export Azure env vars for Trusted Signing
-        shell: pwsh
-        run: |
-          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $env:GITHUB_ENV
-          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $env:GITHUB_ENV
-          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $env:GITHUB_ENV
-          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $env:GITHUB_ENV
-
-      - name: Debug GitHub context
-        run: |
-          echo "Ref: $GITHUB_REF"
-          echo "Repository: $GITHUB_REPOSITORY"
-
-      - name: Verify Azure env vars
-        shell: pwsh
-        run: |
-          Get-ChildItem Env:AZURE*
-
-      #          echo "Federated token file:"
-      #          Test-Path $env:AZURE_FEDERATED_TOKEN_FILE
-
-      # Build Windows artifacts
-      - name: Build Windows App
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-          ELECTRON_BUILDER_HTTP_TIMEOUT: 600000
-          ELECTRON_BUILDER_HTTP_RETRY: 5
-        run: npm run release
 
   #      - name: Install AzureSignTool
   #        run: dotnet tool install --global AzureSignTool
@@ -125,117 +128,121 @@ jobs:
   #        with:
   #          files: dist/*.exe
 
-  #  publish_linux:
-  #    name: "Publish Linux x64"
-  #    runs-on: ubuntu-latest
-  #
-  #    steps:
-  #      - name: Check out Git repository
-  #        uses: actions/checkout@v4
-  #
-  #      - name: Install Node.js and NPM
-  #        uses: actions/setup-node@v4
-  #        with:
-  #          node-version: 22
-  #
-  #      - name: Install libraries
-  #        run: sudo apt-get install libfontconfig1-dev --fix-missing
-  #
-  #      - name: Install dependencies
-  #        run: npm install
-  #
-  #      - name: Build and release app
-  #        env:
-  #          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-  #        run: npm run release
-  #
-  #  # This needs it's own build
-  #  # https://github.com/ChurchApps/FreeShow/issues/562
-  #  publish_linux_arm:
-  #    name: "Publish Linux arm64"
-  #    runs-on: ubuntu-24.04-arm
-  #
-  #    steps:
-  #      - name: Check out Git repository
-  #        uses: actions/checkout@v4
-  #
-  #      - name: Install Node.js and NPM
-  #        uses: actions/setup-node@v4
-  #        with:
-  #          node-version: 22
-  #
-  #      - name: Install libraries
-  #        run:
-  #          |
-  #          sudo apt-get update
-  #          sudo apt-get install -y libfontconfig1-dev uuid-dev --fix-missing
-  #
-  #      # WIDEVINE
-  #      # - name: Use stock Electron on ARM64
-  #      #   run: npm run replace-electron
-  #
-  #      - name: Install dependencies
-  #        run: npm install
-  #
-  #      - name: Install FPM
-  #        run:
-  #          |
-  #          sudo apt-get install ruby ruby-dev build-essential
-  #          sudo gem install --no-document fpm
-  #
-  #      # wait because this will only publish if the draft exists
-  #      - name: Sleep for 1.5 minute
-  #        run: sleep 90s
-  #        shell: bash
-  #
-  #      - name: Build and release app
-  #        env:
-  #          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-  #          USE_SYSTEM_FPM: true
-  #        run: npm run release:arm64
 
-  publish_mac:
-    name: "Publish MacOS"
-    #    needs: check_branch
-    #    if: needs.check_branch.outputs.is_correct_branch == 'true'
-    runs-on: macos-latest
+    publish_linux:
+      name: "Publish Linux x64"
+      runs-on: ubuntu-latest
+ 
+      steps:
+        - name: Check out Git repository
+          uses: actions/checkout@v4
+  
+        - name: Install Node.js and NPM
+          uses: actions/setup-node@v4
+          with:
+            node-version: 22
+  
+        - name: Install libraries
+          run:
+            |
+            sudo apt-get update 
+            sudo apt-get install libfontconfig1-dev --fix-missing
+  
+        - name: Install dependencies
+          run: npm install
+  
+        - name: Build and release app
+          env:
+            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          run: npm run release
+  
+    # This needs it's own build
+    # https://github.com/ChurchApps/FreeShow/issues/562
+    publish_linux_arm:
+      name: "Publish Linux arm64"
+      runs-on: ubuntu-24.04-arm
+  
+      steps:
+        - name: Check out Git repository
+          uses: actions/checkout@v4
+  
+        - name: Install Node.js and NPM
+          uses: actions/setup-node@v4
+          with:
+            node-version: 22
+  
+        - name: Install libraries
+          run:
+            |
+            sudo apt-get update
+            sudo apt-get install -y libfontconfig1-dev uuid-dev --fix-missing
+  
+        # WIDEVINE
+        # - name: Use stock Electron on ARM64
+        #   run: npm run replace-electron
+  
+        - name: Install dependencies
+          run: npm install
+  
+        - name: Install FPM
+          run:
+            |
+            sudo apt-get install ruby ruby-dev build-essential
+            sudo gem install --no-document fpm
+  
+        # wait because this will only publish if the draft exists
+        - name: Sleep for 1.5 minute
+          run: sleep 90s
+          shell: bash
+  
+        - name: Build and release app
+          env:
+            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+            USE_SYSTEM_FPM: true
+          run: npm run release:arm64
 
-    steps:
-      - name: Check out Git repository
-        uses: actions/checkout@v4
-
-      - name: Install Node.js and NPM
-        uses: actions/setup-node@v4
-        with:
-          node-version: 22
-
-      # Change Python version: https://github.com/nodejs/node-gyp/issues/2869
-      - name: Install Python 3.11
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.11"
-
-      # This probably does not make any difference.
-      - name: Install node-gyp
-        run: npm install -g node-gyp
-
-      - name: Install dependencies
-        run: npm install
-
-      - name: Install dmg-license
-        run: npm i dmg-license
-
-      # for some reason the build command don't continue after the rollup build
-      - name: Sleep for 3 minutes
-        run: sleep 180
-        shell: bash
-
-      - name: Build and release app
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-          CSC_LINK: ${{ secrets.CSC_LINK }}
-          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
-          APPLE_ID: ${{ secrets.APPLEID }}
-          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
-          APPLE_TEAM_ID: ${{ secrets.APPLETEAMID }}
-        run: npm run release
+#  publish_mac:
+#    name: "Publish MacOS"
+#    #    needs: check_branch
+#    #    if: needs.check_branch.outputs.is_correct_branch == 'true'
+#    runs-on: macos-latest
+#
+#    steps:
+#      - name: Check out Git repository
+#        uses: actions/checkout@v4
+#
+#      - name: Install Node.js and NPM
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 22
+#
+#      # Change Python version: https://github.com/nodejs/node-gyp/issues/2869
+#      - name: Install Python 3.11
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: "3.11"
+#
+#      # This probably does not make any difference.
+#      - name: Install node-gyp
+#        run: npm install -g node-gyp
+#
+#      - name: Install dependencies
+#        run: npm install
+#
+#      - name: Install dmg-license
+#        run: npm i dmg-license
+#
+#      # for some reason the build command don't continue after the rollup build
+#      - name: Sleep for 3 minutes
+#        run: sleep 180
+#        shell: bash
+#
+#      - name: Build and release app
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+#          CSC_LINK: ${{ secrets.CSC_LINK }}
+#          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
+#          APPLE_ID: ${{ secrets.APPLEID }}
+#          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
+#          APPLE_TEAM_ID: ${{ secrets.APPLETEAMID }}
+#        run: npm run release
